# Generated by Django 3.2.4 on 2021-07-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Loaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('lender', models.CharField(max_length=100)),
                ('return_date', models.DateField()),
                ('guarantors', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
